//
// Created by Yomi Ndu on 01/04/2024.
//

#ifndef INC_2DPHYSICSENGINE_CONSTANTS_H
#define INC_2DPHYSICSENGINE_CONSTANTS_H

const int FPS = 60;
const int MILLISECONDS_PER_FRAME = 1000 / FPS;
const int PIXELS_PER_METER = 50;

#endif //INC_2DPHYSICSENGINE_CONSTANTS_H
